/** 系统权限码唯一注册表；seed、API 和 Web 逐步从此处引用。 */
export const PERMISSIONS = {
  userQuery: "system:user:query",
  userCreate: "system:user:create",
  userUpdate: "system:user:update",
  userDelete: "system:user:delete",
  userAssignRole: "system:user:assign-role",
  roleQuery: "system:role:query",
  roleCreate: "system:role:create",
  roleUpdate: "system:role:update",
  roleDelete: "system:role:delete",
  roleAssign: "system:role:assign",
  menuQuery: "system:menu:query",
  menuCreate: "system:menu:create",
  menuUpdate: "system:menu:update",
  menuDelete: "system:menu:delete",
  logQuery: "system:log:query",
  sessionQuery: "system:session:query",
  sessionRevoke: "system:session:revoke",
  dictQuery: "system:dict:query",
  dictCreate: "system:dict:create",
  dictUpdate: "system:dict:update",
  dictDelete: "system:dict:delete",
  configQuery: "system:config:query",
  configCreate: "system:config:create",
  configUpdate: "system:config:update",
  configDelete: "system:config:delete",
  notificationCreate: "system:notification:create",
  departmentQuery: "system:dept:query",
  departmentCreate: "system:dept:create",
  departmentUpdate: "system:dept:update",
  departmentDelete: "system:dept:delete",
  announcementQuery: "system:announcement:query",
  announcementCreate: "system:announcement:create",
  announcementUpdate: "system:announcement:update",
  announcementDelete: "system:announcement:delete",
} as const

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]
